"""bidiwave — WebDriver BiDi for Python."""

from bidiwave.client import BiDiClient
from bidiwave.config import ClientConfig
from bidiwave.convenience.page import Page
from bidiwave.events.dispatcher import EventDispatcher
from bidiwave.events.handlers import AsyncHandler, Subscription
from bidiwave.exceptions import (
    BiDiConnectionError,
    BiDiError,
    BiDiTimeoutError,
    CapabilityError,
    CommandError,
    DetachedShadowRootError,
    ElementNotInteractableError,
    InsecureCertificateError,
    InvalidArgumentError,
    InvalidSessionError,
    InvalidWebExtensionError,
    JavaScriptError,
    MoveTargetOutOfBoundsError,
    NoSuchAlertError,
    NoSuchCookieError,
    NoSuchElementError,
    NoSuchFrameError,
    NoSuchShadowRootError,
    NoSuchUserContextError,
    NoSuchWindowError,
    ProtocolError,
    SessionError,
    SessionNotCreatedError,
    SessionNotFoundError,
    StaleElementReferenceError,
    TimeoutError,
    UnableToCaptureScreenError,
    UnknownCommandError,
    UnsupportedOperationError,
)
from bidiwave.modules.browsing import BrowsingContext
from bidiwave.modules.cdp import CDPModule
from bidiwave.modules.emulation import EmulationModule
from bidiwave.modules.input import InputModule
from bidiwave.modules.log import LogModule
from bidiwave.modules.network import NetworkModule
from bidiwave.modules.permissions import PermissionsModule
from bidiwave.modules.preload import PreloadModule
from bidiwave.modules.script import ScriptModule
from bidiwave.modules.session import SessionModule
from bidiwave.modules.storage import StorageModule
from bidiwave.modules.webextension import WebExtensionModule
from bidiwave.protocol.capabilities import Capabilities
from bidiwave.protocol.commands import ViewportSize
from bidiwave.protocol.events import (
    BrowsingContextCreatedEvent,
    BrowsingContextDestroyedEvent,
    BrowsingContextDOMContentLoadedEvent,
    BrowsingContextDownloadEndEvent,
    BrowsingContextDownloadWillBeginEvent,
    BrowsingContextFragmentNavigatedEvent,
    BrowsingContextHistoryUpdatedEvent,
    BrowsingContextLoadEvent,
    BrowsingContextNavigationAbortedEvent,
    BrowsingContextNavigationCommittedEvent,
    BrowsingContextNavigationCompletedEvent,
    BrowsingContextNavigationFailedEvent,
    BrowsingContextNavigationStartedEvent,
    BrowsingContextUserPromptClosedEvent,
    BrowsingContextUserPromptOpenedEvent,
    InputFileDialogOpenedEvent,
    NetworkAuthRequiredEvent,
    NetworkBeforeRequestSentEvent,
    NetworkDataReceivedEvent,
    NetworkFetchErrorEvent,
    NetworkResponseCompletedEvent,
    NetworkResponseStartedEvent,
    NetworkSamplingStateChangedEvent,
    ScriptMessageEvent,
    ScriptRealmCreatedEvent,
    ScriptRealmDestroyedEvent,
)
from bidiwave.protocol.remote_value import (
    ArrayBufferValue,
    ArrayValue,
    BigIntValue,
    BooleanValue,
    ChannelValue,
    DateValue,
    ErrorValue,
    GeneratorValue,
    HandleValue,
    HTMLCollectionValue,
    MapValue,
    NodeListValue,
    NodeValue,
    NullValue,
    NumberValue,
    ObjectValue,
    PromiseValue,
    ProxyValue,
    RegExpValue,
    RemoteValue,
    SetValue,
    StringValue,
    TypedArrayValue,
    UndefinedValue,
    WeakMapValue,
    WeakSetValue,
    WindowValue,
)
from bidiwave.protocol.results import (
    AddCacheOverrideResult,
    AddPreloadScriptResult,
    Cookie,
    InputSource,
    KeyAction,
    LocateNodesResult,
    PointerAction,
    RealmInfo,
    ResponseBodyResult,
    ScriptAddPreloadScriptResult,
    UserContextInfo,
    Viewport,
    WheelAction,
)
from bidiwave.transport.connection import TransportConfig

__version__ = "1.8.0"

__all__ = [
    "AddCacheOverrideResult",
    "AddPreloadScriptResult",
    "ArrayBufferValue",
    "ArrayValue",
    "AsyncHandler",
    "BigIntValue",
    "BiDiClient",
    "BiDiConnectionError",
    "BiDiError",
    "BiDiTimeoutError",
    "BooleanValue",
    "BrowsingContext",
    "BrowsingContextCreatedEvent",
    "BrowsingContextDestroyedEvent",
    "BrowsingContextDOMContentLoadedEvent",
    "BrowsingContextDownloadEndEvent",
    "BrowsingContextDownloadWillBeginEvent",
    "BrowsingContextFragmentNavigatedEvent",
    "BrowsingContextHistoryUpdatedEvent",
    "BrowsingContextLoadEvent",
    "BrowsingContextNavigationAbortedEvent",
    "BrowsingContextNavigationCompletedEvent",
    "BrowsingContextNavigationCommittedEvent",
    "BrowsingContextNavigationFailedEvent",
    "BrowsingContextNavigationStartedEvent",
    "BrowsingContextUserPromptClosedEvent",
    "BrowsingContextUserPromptOpenedEvent",
    "Capabilities",
    "CapabilityError",
    "CDPModule",
    "ChannelValue",
    "ClientConfig",
    "CommandError",
    "Cookie",
    "DateValue",
    "DetachedShadowRootError",
    "ElementNotInteractableError",
    "EmulationModule",
    "ErrorValue",
    "EventDispatcher",
    "GeneratorValue",
    "HandleValue",
    "HTMLCollectionValue",
    "InsecureCertificateError",
    "InvalidArgumentError",
    "InvalidSessionError",
    "InvalidWebExtensionError",
    "InputFileDialogOpenedEvent",
    "InputModule",
    "InputSource",
    "JavaScriptError",
    "KeyAction",
    "LocateNodesResult",
    "LogModule",
    "MapValue",
    "MoveTargetOutOfBoundsError",
    "NetworkAuthRequiredEvent",
    "NetworkBeforeRequestSentEvent",
    "NetworkDataReceivedEvent",
    "NetworkFetchErrorEvent",
    "NetworkModule",
    "NetworkResponseCompletedEvent",
    "NetworkResponseStartedEvent",
    "NetworkSamplingStateChangedEvent",
    "NoSuchAlertError",
    "NoSuchCookieError",
    "NoSuchElementError",
    "NoSuchFrameError",
    "NoSuchShadowRootError",
    "NoSuchUserContextError",
    "NoSuchWindowError",
    "NodeListValue",
    "NodeValue",
    "NullValue",
    "NumberValue",
    "ObjectValue",
    "Page",
    "PermissionsModule",
    "PointerAction",
    "PreloadModule",
    "PromiseValue",
    "ProtocolError",
    "ProxyValue",
    "RealmInfo",
    "RegExpValue",
    "RemoteValue",
    "ResponseBodyResult",
    "ScriptAddPreloadScriptResult",
    "ScriptMessageEvent",
    "ScriptModule",
    "ScriptRealmCreatedEvent",
    "ScriptRealmDestroyedEvent",
    "SessionError",
    "SessionModule",
    "SessionNotCreatedError",
    "SessionNotFoundError",
    "SetValue",
    "StaleElementReferenceError",
    "StorageModule",
    "StringValue",
    "Subscription",
    "TimeoutError",
    "TransportConfig",
    "TypedArrayValue",
    "UnableToCaptureScreenError",
    "UndefinedValue",
    "UnknownCommandError",
    "UnsupportedOperationError",
    "UserContextInfo",
    "Viewport",
    "ViewportSize",
    "WeakMapValue",
    "WeakSetValue",
    "WebExtensionModule",
    "WheelAction",
    "WindowValue",
    "__version__",
]
