"""Constantes del protocolo WebDriver BiDi."""

# Command methods
SESSION_NEW = "session.new"
SESSION_STATUS = "session.status"
SESSION_END = "session.end"
SESSION_SUBSCRIBE = "session.subscribe"
SESSION_UNSUBSCRIBE = "session.unsubscribe"
BROWSING_CREATE_CONTEXT = "browsingContext.create"
BROWSING_NAVIGATE = "browsingContext.navigate"
BROWSING_CLOSE = "browsingContext.close"
BROWSING_GET_TREE = "browsingContext.getTree"
BROWSING_CAPTURE_SCREENSHOT = "browsingContext.captureScreenshot"
BROWSING_RELOAD = "browsingContext.reload"
BROWSING_TRAVERSE_HISTORY = "browsingContext.traverseHistory"
BROWSING_HANDLE_USER_PROMPT = "browsingContext.handleUserPrompt"
BROWSING_PRINT = "browsingContext.print"
BROWSING_LOCATE_NODES = "browsingContext.locateNodes"
BROWSING_ACTIVATE = "browsingContext.activate"
BROWSING_SET_VIEWPORT = "browsingContext.setViewport"
SCRIPT_EVALUATE = "script.evaluate"
SCRIPT_CALL_FUNCTION = "script.callFunction"
SCRIPT_DISOWN = "script.disown"
SCRIPT_GET_REALMS = "script.getRealms"
NETWORK_ADD_INTERCEPT = "network.addIntercept"
NETWORK_REMOVE_INTERCEPT = "network.removeIntercept"
NETWORK_CONTINUE_REQUEST = "network.continueRequest"
NETWORK_CONTINUE_RESPONSE = "network.continueResponse"
NETWORK_FAIL_REQUEST = "network.failRequest"
NETWORK_PROVIDE_RESPONSE = "network.provideResponse"
NETWORK_CONTINUE_WITH_AUTH = "network.continueWithAuth"
NETWORK_CANCEL_AUTH = "network.cancelAuth"
INPUT_PERFORM_ACTIONS = "input.performActions"
INPUT_RELEASE_ACTIONS = "input.releaseActions"
INPUT_SET_FILES = "input.setFiles"
STORAGE_GET_COOKIES = "storage.getCookies"
STORAGE_SET_COOKIE = "storage.setCookie"
STORAGE_DELETE_COOKIES = "storage.deleteCookies"

# Event types
LOG_ENTRY_ADDED = "log.entryAdded"
BROWSING_CONTEXT_CREATED = "browsingContext.contextCreated"
BROWSING_CONTEXT_DESTROYED = "browsingContext.contextDestroyed"
BROWSING_CONTEXT_NAVIGATED = "browsingContext.navigationStarted"
SCRIPT_MESSAGE = "script.message"
NETWORK_BEFORE_REQUEST_SENT = "network.beforeRequestSent"
NETWORK_RESPONSE_COMPLETED = "network.responseCompleted"
NETWORK_FETCH_ERROR = "network.fetchError"

# Error codes
INVALID_ARGUMENT = "invalid argument"
INVALID_SESSION = "invalid session"
SESSION_NOT_CREATED = "session not created"
SESSION_NOT_FOUND = "session not found"
UNKNOWN_COMMAND = "unknown command"
UNSUPPORTED_OPERATION = "unsupported operation"
JAVASCRIPT_ERROR = "javascript error"
NO_SUCH_FRAME = "no such frame"
NO_SUCH_WINDOW = "no such window"
TIMEOUT = "timeout"
UNABLE_TO_CAPTURE_SCREEN = "unable to capture screen"